on:
  push:
    branches:
      - main
jobs:
  # 每个job的构建环境及steps所做操作
  build:
  	# 该job在什么环境下运行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. 
